# ques 1


In [1]:
import numpy as np
np.arr=[]
for np.arr in range(2,50,3):
    print(np.arr,end=" ")

2 5 8 11 14 17 20 23 26 29 32 35 38 41 44 47 

# ques 2

In [2]:
import numpy as np
lis1=[]
lis2=[]



lis1=[int(x) for x in input().split()]
lis2=[int(x) for x in input().split()]
print(lis1)
print(lis2)
arr1=np.asarray(lis1)
arr2=np.asarray(lis2)
print(arr1)
print(arr2)
arr3=np.concatenate((arr1,arr2))
print(arr3)
np.sort(arr3)

5 7 8 2 1
3 7 4 6 9
[5, 7, 8, 2, 1]
[3, 7, 4, 6, 9]
[5 7 8 2 1]
[3 7 4 6 9]
[5 7 8 2 1 3 7 4 6 9]


array([1, 2, 3, 4, 5, 6, 7, 7, 8, 9])

# ques 3

In [3]:
arr1=np.array([1,2,3,6,8])
arr2=np.array([[3,4,5],[23,5,78]])
arr3=np.array([[[1,2,33],[3,6,9]],[[0.,3,5],[4,6,5]]])
print(arr1.ndim,arr1.size)
print(arr2.ndim,arr2.size)
print(arr3.ndim,arr3.size)

1 5
2 6
3 12


# ques 4

In [4]:
n=int(input())
arr=np.arange(n)
print(arr)
print(arr.ndim)

arr2=arr[np.newaxis,:]
print(arr2)
print(arr2.ndim)

arr3=np.expand_dims(arr,axis=1)
print(arr3)
print(arr3.ndim)

5
[0 1 2 3 4]
1
[[0 1 2 3 4]]
2
[[0]
 [1]
 [2]
 [3]
 [4]]
2


# ques 5

In [5]:
a=(np.arange(1,10).reshape(3,3))
print(a)
b=(np.arange(11,20).reshape(3,3))
print(b)
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


# ques 6

In [6]:
arr=[1,2,3,2,4,2,3]
print(arr)
unique,count=np.unique(arr,return_counts=True)
print(unique)
print(count)

[1, 2, 3, 2, 4, 2, 3]
[1 2 3 4]
[1 3 2 1]
